### PR TITLE
Release 1.0.2

### LINKED ISSUE #33: Release latest version with Stencil 0.9.0
This blocks https://github.com/krzysztofzablocki/Sourcery/issues/259
Thanks!

### PR DESCRIPTION
**Pull request by AliSoftware**
Closes #33 \cc @ilyapuchka

After merge:

* [ ] `pod trunk push`
* [ ] `rake changelog:reset`

### CODE REVIEW

**Comment by djbe** [comment]
Could it be that you have an older CocoaPods? The diff on the generated xcode project implies that you do.

Also, maybe merge #12 before this release, unless you want to make some modifications?

**Comment by AliSoftware** [comment]
Just updated to cp 1.0.2 before doing my pod update `StencilSwiftKit` and version in `Podfile.lock` seems to match? 

About #12 wasn't sure it was finished?

**Comment by djbe** [comment]
Dunno, both the filters and the tags are documented (even the new map tag). 

CocoaPods 1.0.2? You probably mean 1.2.0? The only reason I mentioned it, was because of the `Pods.xcodepoj` changes, which seem to go down an Xcode version.

**Comment by AliSoftware** [comment]
I actually meant 1.2.1 😄

```sh
$ pod --version
1.2.1
```

**Comment by djbe** [comment]
Huh, weird. Anyway, when I try a `pod install/update`, nothing changes, so ignore what I said about CocoaPods.

**Comment by AliSoftware** [comment]
We should merge #36 first; then rebase this release on top of that (or merge master into this release) and merge/deploy the release to CP :wink:

**Comment by AliSoftware** [comment]
@djbe please tell me once you've approved/merged #36 and (rebased and) approved the current #34 and I'll do a new release in CP right after :)

**Pull request merged**
